# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/spring5-recipe-app

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Generate cumulative pom.xml checksum
          command: |
            find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
            sort -o ~/pom-checksum ~/pom-checksum.tmp
          when: always

      # Download and cache dependencies
      - restore_cache:
          keys:
            - spring5-recipe-app-{{ checksum "~/pom-checksum" }}
            - spring5-recipe-app-

      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: spring5-recipe-app-{{ checksum "~/pom-checksum" }}

      - run: mvn package

          - run:
              name: Save test results
              command: |
                mkdir -p ~/test-results/junit/
                find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
              when: always

      - store_test_results:
          path: ~/test-results

            - store_artifacts:
                path: my-service/target/my-service.jar
